language: c

compiler:
  - gcc

install:
  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build
  - cmake -DENABLE_GCOV=ON ..
  - cmake --build .
  - ./tests

after_success:
  - coveralls --root .. --exclude="build/googletest-src" --exclude="src/test" -E ".*/feature_tests.*" -E ".*/CMake.*"
