language: c

addons:
  sonarcloud:
    organization: eliezio-github

compiler:
  - gcc

before_install:
  - ccache -z

install:
  - pip install --user codecov

script:
  - cmake -DENABLE_GCOV=ON .
  # Wrap the compiled app in sonarqube
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build .
  - ./tests --gtest_output=xml

after_success:
  - ccache -s
  - codecov
  - sonar-scanner

cache:
  ccache: true
  directories:
    - '$HOME/.sonar/cache'
