language: c

compiler:
  - gcc

install:
  - pip install --user codecov

script:
  - mkdir build && cd build
  - cmake -DENABLE_GCOV=ON ..
  - cmake --build .
  - ./tests

after_success:
  - codecov --root ..
