language: c

addons:
  sonarcloud:
    organization: eliezio-github

matrix:
  include:
    - os: linux
      compiler: gcc
      env: OS_NAME=Linux BW_ARCH=linux-x86-64
    - os: osx
      compiler: clang
      env: OS_NAME=Darwin BW_ARCH=macosx-x86

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - ccache -z

script:
  - cmake -DENABLE_GCOV=ON .
  # Wrap the compiled app in sonarqube
  - build-wrapper-$BW_ARCH --out-dir bw-output cmake --build .
  - ./tests --gtest_output=xml:test_reports/

after_success:
  - ccache -s
  - find . -type f -name '*.gcno' -exec gcov -pb {} +
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sonar-scanner; fi

before_deploy:
  - cpack -G TGZ .
  - export VERSION_SHORT="$(cat version_short.txt)"

deploy:
  provider: releases
  api_key:
  - secure: "FjUPmFKJ/BglsSSCPfrQwRpT039hn9mAVMNgw/fbsmnQQyDOFM6U7l/a70ett8wmpyuDf62zdC3Ka/b2Jcbu90YZPhCkW69cUnj8XNR1NOComy4EmvuNUqSXkVDmbyd7ascWqjfzxUHg7tYIIz9RU360F6XzlEixKT2jVaCqTQUtJH0im6KqmPSX3mcLmLRUJ4HIL8+D1jkWKpIeucLzdGEbjqfcrL7OHsTBkK2AZP8PMu0tv0fxoNmiIk6uxv7j3FHvLR6nsaannsKsiNk2r0o+zMx0iZXDSyABIF5nOFF6MG5qsbqX+mfDZgOuwA155a4zz70LWyLjrlZ+y4WXvSSMrof6XdDO8dN5Zf0z1Z1rU9LRpfKYPOKMPOk+iOZldQD6RCyhSNQzWhUahW96sQqbgvmno2I6e1uNO2dswfEgQo+reUEQI0avzixwFj7nK11sCkUDgfMvHfD93gjk7k3mpNkTFhcxwkqL1L62jmloAdulZvFj7NMVlANGvE2mnqiP4Q5nQu0D6cCqrAiVRt6/5xlRqcXNx33bQEuypQvXMBRuwB5J/BvrA6t94frg5BtUSraMPIqipXeC1CwhjyvqzygoQCOPtumw3Rzr2FmB7oQ+zocBZx/6l6WBXhhfAJyNeu6dIpbHZgxEVX0ZbnReDCHmg4GN2JTLZ6CzIFE="
  file: marketmaker-cli-$VERSION_SHORT-$OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: true

cache:
  ccache: true
  directories:
    - '$HOME/.sonar/cache'

