language: c

addons:
  sonarcloud:
    organization: eliezio-github

compiler:
  - gcc

before_install:
  - ccache -z

install:
  - pip install --user codecov

script:
  - mkdir build && cd build
  - cmake -DENABLE_GCOV=ON ..
  # Wrap the compiled app in sonar qube
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build .
  - cd ..
  - cmake --build .
  - sonar-scanner
  - ./tests

after_success:
  - ccache -s
  - codecov --root ..

cache:
  ccache: true
  directories:
    - '$HOME/.sonar/cache'
